#!/usr/bin/env python3
"""
Generate lighter variants of DUL for the ECMO benchmark.

  lite  - dul:associatedWith is neither transitive nor symmetric
          (removes its owl:TransitiveProperty, owl:SymmetricProperty and the
          self-inverse axiom `associatedWith owl:inverseOf associatedWith`,
          which entails symmetry on its own)
  flat  - no property in DUL is transitive or symmetric
          (same removals for every property)

Everything else (hierarchy, domains/ranges, inverses between distinct
properties, property chains, disjointness) is kept. A comment is added to the
ontology header listing what was removed.

Usage:
  python make_dul_variants.py [DUL.owl] [-o OUTDIR]     # writes DUL-lite.ttl, DUL-flat.ttl

Default OUTDIR: ../data/dul-variants (relative to this script).

Requires rdflib (pip install rdflib). The generated files are committed in
../data/dul-variants/, so the benchmark itself does not need rdflib.
"""
import argparse
from pathlib import Path

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import OWL, RDF, RDFS

DUL = Namespace("http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#")
DUL_ONTOLOGY = URIRef("http://www.ontologydesignpatterns.org/ont/dul/DUL.owl")
DUL_URL = "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl"


def load(path):
    g = Graph()
    for fmt in ("turtle", "xml"):  # DUL.owl is actually Turtle
        try:
            g.parse(path, format=fmt)
            return g
        except Exception:
            g = Graph()
    raise SystemExit(f"Cannot parse {path} as Turtle or RDF/XML")


def strip(g, props, label):
    removed = []
    for p in props:
        for t in ((p, RDF.type, OWL.TransitiveProperty),
                  (p, RDF.type, OWL.SymmetricProperty),
                  (p, OWL.inverseOf, p)):
            if t in g:
                g.remove(t)
                removed.append(f"{p.split('#')[-1]} {t[1].n3(g.namespace_manager)} {t[2].n3(g.namespace_manager)}")
    note = (f"ECMO benchmark variant '{label}' of DUL, generated by make_dul_variants.py. "
            f"Removed axioms: " + "; ".join(sorted(removed)))
    g.add((DUL_ONTOLOGY, RDFS.comment, Literal(note)))
    return removed


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dul", nargs="?", help=f"DUL file (default: download {DUL_URL})")
    ap.add_argument("-o", "--outdir",
                    default=str(Path(__file__).resolve().parent.parent / "data" / "dul-variants"))
    args = ap.parse_args()
    src = args.dul or DUL_URL
    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)

    base = load(src)
    props = {s for s in base.subjects(RDF.type, OWL.TransitiveProperty)} \
        | {s for s in base.subjects(RDF.type, OWL.SymmetricProperty)} \
        | {s for s, o in base.subject_objects(OWL.inverseOf) if s == o}

    for label, selected in (("lite", {DUL.associatedWith}), ("flat", props)):
        g = Graph()
        for prefix, ns in base.namespaces():
            g.bind(prefix, ns)
        g += base
        removed = strip(g, sorted(selected), label)
        path = out / f"DUL-{label}.ttl"
        g.serialize(path, format="turtle")
        print(f"{path}: {len(g)} triples, removed {len(removed)} axioms")
        for r in removed:
            print(f"   - {r}")


if __name__ == "__main__":
    main()
